// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20250228195952_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45507"),
                            Descripcion = "Descripcion",
                            Nombre = "Test",
                            Resumen = "Resumen"
                        },
                        new
                        {
                            CategoriaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45508"),
                            Descripcion = "Descripcion2",
                            Nombre = "Test2",
                            Resumen = "Resumen2"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tareas", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45509"),
                            CategoriaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45507"),
                            Descripcion = "Descripcion1",
                            FechaCreacion = new DateTime(2025, 2, 28, 19, 39, 21, 909, DateTimeKind.Utc).AddTicks(1710),
                            IsActive = true,
                            PrioridadTarea = 2,
                            Titulo = "Tarea1"
                        },
                        new
                        {
                            TareaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45510"),
                            CategoriaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45507"),
                            Descripcion = "Descripcion2",
                            FechaCreacion = new DateTime(2025, 2, 28, 19, 39, 21, 909, DateTimeKind.Utc).AddTicks(1717),
                            IsActive = true,
                            PrioridadTarea = 1,
                            Titulo = "Tarea2"
                        },
                        new
                        {
                            TareaId = new Guid("8f31917c-5d9b-42d8-89a2-8d23d72c3088"),
                            CategoriaId = new Guid("264b59f3-2346-4f72-b1fc-a6842bb45508"),
                            Descripcion = "Descripcion3",
                            FechaCreacion = new DateTime(2025, 2, 28, 19, 39, 21, 909, DateTimeKind.Utc).AddTicks(1720),
                            IsActive = false,
                            PrioridadTarea = 0,
                            Titulo = "Tarea3"
                        });
                });

            modelBuilder.Entity("EntityFramework.Models.Tarea", b =>
                {
                    b.HasOne("EntityFramework.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EntityFramework.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
